[package]
name = "rocket-counter"
version = "0.1.0"
authors = ["Lorenzo Manacorda <lorenzo@mailbox.org>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
serde = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version = "0.3.3"
features = ["handlebars_templates"]
